=== mentaman/cspat/trunk/Course/513 Electronic Commerce Technology/P3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/P3" xmlns:tns="http://www.example.org/P3" elementFormDefault="qualified">

    <element name="Orders" type="tns:Orders"></element>



    <complexType name="Orders">
    	<sequence>
    		<element name="order" type="tns:Order"></element>
    	</sequence>
    </complexType>

    <complexType name="Order">
    	<sequence>
    		<element name="id" type="string"></element>
    		<element name="description" type="string"></element>
    		<element name="submissionDate" type="date" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="shippingAddress" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="products" type="tns:Products" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="Products">
    	<sequence>
    		<element name="product" type="tns:Product" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="Product">
    	<sequence>
    		<element name="id" type="string"></element>
    		<element name="name" type="string"></element>
    		<element name="description" type="string"></element>
    		<element name="quantities">
    			<simpleType>
    				<restriction base="int">
    					<minInclusive value="1"></minInclusive>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="price">
    			<simpleType>
    				<restriction base="double">
    					<minInclusive value="0"></minInclusive>
    				</restriction>
    			</simpleType>
    		</element>
    	</sequence>
    </complexType>

</schema>

=== mentaman/cspat/Course/513 Electronic Commerce Technology/P3.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Orders xmlns:tns="http://www.example.org/P3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/P3 P3.xsd ">
  <tns:order>
    <tns:id>1</tns:id>
    <tns:description>order 1</tns:description>
    <tns:submissionDate>2011-04-04</tns:submissionDate>
    <tns:shippingAddress>NCSU</tns:shippingAddress>
    <tns:products>
      <tns:product>
        <tns:id>p1</tns:id>
        <tns:name>product1</tns:name>
        <tns:description>product 1</tns:description>
        <tns:quantities>1</tns:quantities>
        <tns:price>10.0</tns:price>
      </tns:product>
      <tns:product>
        <tns:id>p2</tns:id>
        <tns:name>product2</tns:name>
        <tns:description>product 2</tns:description>
        <tns:quantities>10</tns:quantities>
        <tns:price>5</tns:price>
      </tns:product>
    </tns:products>
  </tns:order>
</tns:Orders>
